[package]
name = "wonder"
version = "0.1.0"
authors = ["Chris Wiggins <email@chriswiggins.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
strum = "0.20"
strum_macros = "0.20"